<script src="<?= base_url('lib/jquery/jquery.min.js') ?>"></script>
<script src="<?= base_url('lib/jquery/jquery-migrate.min.js') ?>"></script>
<script src="<?= base_url('lib/popper/popper.min.js') ?>"></script>
<script src="<?= base_url('lib/bootstrap/js/bootstrap.min.js') ?>"></script>
<script src="<?= base_url('lib/easing/easing.min.js') ?>"></script>
<script src="<?= base_url('lib/counterup/jquery.waypoints.min.js') ?>"></script>
<script src="<?= base_url('lib/counterup/jquery.counterup.js') ?>"></script>
<script src="<?= base_url('lib/owlcarousel/owl.carousel.min.js') ?>"></script>
<script src="<?= base_url('lib/lightbox/js/lightbox.min.js') ?>"></script>
<script src="<?= base_url('lib/typed/typed.min.js') ?>"></script>
<script src="<?= base_url('lib/contactform/contactform.js') ?>"></script>
<script src="<?= base_url('js/devfolio/main.js') ?>"></script>